### ISSUE TITLE
[Feature Request] Ability to Setup a Field with Default Keys/Values

### ISSUE THREAD

**Issue by luxlogica** [OblikStudio/kirby-json#1]
Hi there! Thank you for such a great plugin!

I'm trying to build an interface for users to edit Structured Data in their websites, and I thought the JSON field might be a good fit. Unfortunately, for the kind of use-case I have in mind, rather than giving the user a 'blank' field for them to build a structure from scratch, I'd need to be able to provide them with a ready-made structure, where they fill in (most of) the values.

The idea is that they'd choose the type of Structured Data they need for the page - e.g., 'Local Business' or 'Blog Article' - and I would present them with the appropriate JSON field (with the right key-value pairs already present) for them to fill out.

Is this something that is already possible to do?

If not, then perhaps we could add an extra blueprint option - let's call it 'autobuild' in this example - which the user could use to set out the wanted key-value pairs. Something like this:

``` yml
autobuild:
  jsonfieldname:
    key: keyname
    value: thevalue
    type: object|array|value(default)
```

The value could, of course, be a single value, an array, or an object entered as a yaml hierarchy. Specifying a basic 'Person' Structured Data object from schema.org might look like this:

``` yml
person:
  label: Person Data
  type: json
  keys: false
  values: true
  mutate: false
  autobuild:
    type:
      key: "@type"
      value: Person
    name:
      # we only specify the key, because we purposely want to leave 'value' empty
      key: name
    same:
      # here we leave value empty, but specify the 'type'
      key: sameAs
      type: array
    spouse:
      # here we specify a child-object as the value
      key: spouse
      value:
        type:
          key: "@type"
          value: Person
        name:
          key: name
```

**Comment by yandodov** [comment]
I think this should be possible by using the `default` option in the blueprint, i.e. specifying a default JSON value that the plugin loads and that the user can then modify.

I imagine something like:

```yaml
myfield:
  type: json
  default: '{"foo": "bar", "name": ""}'
```

Could you try that and tell if it works? If not, I might need to make some minor changes. But in general, I think this should be the way to go. Perhaps it could be useful to be able to point `default` to a JSON file and store the default data there instead. Or even, parse the YAML-encoded data as JSON so that this:

```yaml
myfield:
  type: json
  default:
    foo: bar
    name: ''
```

---

However, for structured data that is _meant_ for editing, I think you should try to use [structure fields](https://getkirby.com/docs/reference/panel/fields/structure) instead. I think the JSON field should be used for _generated_ data that you want to visualize and optionally, allow to edit.
